const fs = require('fs');

const path = './data/tourism_spots.json';
const data = JSON.parse(fs.readFileSync(path, 'utf8'));

// We have 146 features. Let's add 54 more to reach 200.
// Let's create an array of new spots
const newSpots = [
  // Madhesh (Needs 8+)
  { id: 'gadhimai-temple', name: 'Gadhimai Temple', category: 'Religion', district: 'Bara', province: 2, province_name: 'Madhesh', description: 'A famous Hindu temple known for the Gadhimai festival held every five years.', facilities: ['Temple', 'Dharmashala'], photo: 'https://images.unsplash.com/photo-1548625361-ecbfd27d5da1?w=500&q=80', lng: 85.034, lat: 26.969 },
  { id: 'chhinnamasta-temple', name: 'Chhinnamasta Bhagawati', category: 'Religion', district: 'Saptari', province: 2, province_name: 'Madhesh', description: 'A renowned Hindu temple dedicated to Goddess Chhinnamasta, highly revered in the eastern Terai.', facilities: ['Temple', 'Offerings'], photo: 'https://images.unsplash.com/photo-1627883606774-601b6c006599?w=500&q=80', lng: 86.808, lat: 26.495 },
  { id: 'jaleshwor-mahadev', name: 'Jaleshwor Mahadev', category: 'Religion', district: 'Mahottari', province: 2, province_name: 'Madhesh', description: 'A historic Shiva temple uniquely situated in water, an important pilgrimage site.', facilities: ['Temple', 'Pond'], photo: 'https://images.unsplash.com/photo-1616422285623-13fc11f26715?w=500&q=80', lng: 85.803, lat: 26.637 },
  { id: 'simraungadh', name: 'Simraungadh', category: 'Heritage', district: 'Bara', province: 2, province_name: 'Madhesh', description: 'Ruins of the ancient capital of the Tirhut kingdom, featuring archaeological artifacts and statues.', facilities: ['Archaeological Site', 'Museum'], photo: 'https://images.unsplash.com/photo-1598285721200-a5cc9de915d3?w=500&q=80', lng: 85.127, lat: 26.837 },
  { id: 'dhanushadham', name: 'Dhanushadham', category: 'Religion', district: 'Dhanusa', province: 2, province_name: 'Madhesh', description: 'A mythological site related to the Ramayana, where a piece of Shiva’s bow is believed to have fallen.', facilities: ['Temple', 'Forest'], photo: 'https://images.unsplash.com/photo-1623190289944-78db0fce29ce?w=500&q=80', lng: 86.035, lat: 26.852 },
  { id: 'sahlesh-phulbari', name: 'Sahlesh Phulbari', category: 'Nature', district: 'Siraha', province: 2, province_name: 'Madhesh', description: 'A sacred forest and garden with a unique orchid that blooms on the first day of the Nepali New Year.', facilities: ['Forest Walk', 'Shrine'], photo: 'https://images.unsplash.com/photo-1440058728956-6f81e3a6acaf?w=500&q=80', lng: 86.357, lat: 26.702 },
  { id: 'bhedia-lake', name: 'Bhedia Lake', category: 'Nature', district: 'Sarlahi', province: 2, province_name: 'Madhesh', description: 'A serene wetland ecosystem in the Terai, excellent for local bird watching and boating.', facilities: ['Boating', 'Picnic Spot'], photo: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=500&q=80', lng: 85.565, lat: 26.966 },
  { id: 'routa-pokhari', name: 'Routa Pokhari', category: 'Nature', district: 'Udayapur', province: 1, province_name: 'Koshi', description: 'A scenic hilltop pond surrounded by dense forest, offering a tranquil retreat and religious significance.', facilities: ['Trekking', 'Camping'], photo: 'https://images.unsplash.com/photo-1517409241944-f2a8dd93dcbd?w=500&q=80', lng: 86.589, lat: 26.901 },
  
  // Sudurpashchim (Needs 7+)
  { id: 'badi-malika', name: 'Badimalika Temple', category: 'Religion', district: 'Bajura', province: 7, province_name: 'Sudurpashchim', description: 'A major pilgrimage site located at a high altitude surrounded by spectacular rolling meadows.', facilities: ['Trekking', 'Temple'], photo: 'https://images.unsplash.com/photo-1552554764-92d6e3f429bc?w=500&q=80', lng: 81.652, lat: 29.431 },
  { id: 'rama-roshan', name: 'Ramaroshan Area', category: 'Nature', district: 'Achham', province: 7, province_name: 'Sudurpashchim', description: 'A stunning complex of 12 lakes and 18 meadows, often called the "Pancha Puri" of the far west.', facilities: ['Hiking', 'Camping', 'Bird Watching'], photo: 'https://images.unsplash.com/photo-1506148386377-5f65756cdd60?w=500&q=80', lng: 81.332, lat: 29.231 },
  { id: 'ghodaghodi-lake', name: 'Ghodaghodi Lake', category: 'Nature', district: 'Kailali', province: 7, province_name: 'Sudurpashchim', description: 'A Ramsar site wetland of immense ecological value, home to crocodiles, turtles, and rare birds.', facilities: ['Bird Watching', 'Boating'], photo: 'https://images.unsplash.com/photo-1466695108335-44674aa2058b?w=500&q=80', lng: 80.933, lat: 28.751 },
  { id: 'tikapur-park', name: 'Tikapur Park', category: 'Nature', district: 'Kailali', province: 7, province_name: 'Sudurpashchim', description: 'One of Nepal’s largest and most beautiful botanical gardens, built by King Mahendra.', facilities: ['Gardens', 'Picnic Areas'], photo: 'https://images.unsplash.com/photo-1585320806297-9794b3e4ce11?w=500&q=80', lng: 81.124, lat: 28.497 },
  { id: 'karnali-bridge', name: 'Karnali Bridge (Chisapani)', category: 'Heritage', district: 'Kailali', province: 7, province_name: 'Sudurpashchim', description: 'An iconic asymmetric, single-tower cable-stayed bridge crossing the mighty Karnali River.', facilities: ['Viewpoint', 'River Rafting Access'], photo: 'https://images.unsplash.com/photo-1616857921360-31622325ab3b?w=500&q=80', lng: 81.282, lat: 28.641 },
  { id: 'shaileshwari-temple', name: 'Shaileshwari Temple', category: 'Religion', district: 'Doti', province: 7, province_name: 'Sudurpashchim', description: 'A prominent Hindu temple in Dipayal, highly revered as one of the major Shakti Peeths in the far-west.', facilities: ['Temple', 'Pilgrimage'], photo: 'https://images.unsplash.com/photo-1628172826725-7ec5ef2c2c04?w=500&q=80', lng: 80.941, lat: 29.263 },
  { id: 'surma-sarovar', name: 'Surma Sarovar', category: 'Nature', district: 'Bajhang', province: 7, province_name: 'Sudurpashchim', description: 'A high-altitude holy lake renowned for its pristine alpine beauty and religious importance.', facilities: ['Trekking', 'Camping'], photo: 'https://images.unsplash.com/photo-1542442828-287217bfb87f?w=500&q=80', lng: 81.189, lat: 29.827 },

  // Karnali (Needs 5+)
  { id: 'kankrebihar', name: 'Kakre Bihar', category: 'Heritage', district: 'Surkhet', province: 6, province_name: 'Karnali', description: 'Intricate ruins of a 12th-century stone temple reflecting both Hindu and Buddhist architectural styles.', facilities: ['Archaeological Park', 'Forest Walk'], photo: 'https://images.unsplash.com/photo-1549429402-9ebef050cc52?w=500&q=80', lng: 81.603, lat: 28.563 },
  { id: 'bulbul-taal', name: 'Bulbule Taal', category: 'Nature', district: 'Surkhet', province: 6, province_name: 'Karnali', description: 'A natural spring-fed lake set within a peaceful park in Birendranagar.', facilities: ['Boating', 'Park'], photo: 'https://images.unsplash.com/photo-1550596334-7bb40a71b6bc?w=500&q=80', lng: 81.632, lat: 28.591 },
  { id: 'limi-valley', name: 'Limi Valley', category: 'Adventure', district: 'Humla', province: 6, province_name: 'Karnali', description: 'A highly remote, culturally rich valley offering off-the-beaten-path trekking near the Tibetan border.', facilities: ['Trekking', 'Homestays'], photo: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&q=80', lng: 81.691, lat: 30.222 },
  { id: 'khali-dada', name: 'Khalidada Viewpoint', category: 'Nature', district: 'Mugu', province: 6, province_name: 'Karnali', description: 'A scenic ridge offering unparalleled views of Rara Lake and the surrounding Himalayan peaks.', facilities: ['Hiking', 'Photography'], photo: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=500&q=80', lng: 82.083, lat: 29.531 },
  { id: 'dullu-heritage', name: 'Dullu Heritage Area', category: 'Heritage', district: 'Dailekh', province: 6, province_name: 'Karnali', description: 'Historical site containing the earliest known Nepali inscription (Damupal\'s inscription) and ancient stone pillars.', facilities: ['Historical Tours', 'Local Guides'], photo: 'https://images.unsplash.com/photo-1570184488340-a35b43ceaf67?w=500&q=80', lng: 81.597, lat: 28.855 },

  // Koshi (Needs 7+)
  { id: 'baraha-kshetra', name: 'Baraha Kshetra', category: 'Religion', district: 'Sunsari', province: 1, province_name: 'Koshi', description: 'One of Nepal’s four major pilgrimage sites, situated at the confluence of the Koshi and Koka rivers.', facilities: ['Temple', 'River Access'], photo: 'https://images.unsplash.com/photo-1598131379391-73898f06536b?w=500&q=80', lng: 87.168, lat: 26.862 },
  { id: 'namche-bazaar', name: 'Namche Bazaar', category: 'Adventure', district: 'Solukhumbu', province: 1, province_name: 'Koshi', description: 'The famous "Gateway to Everest," a bustling Sherpa town nestled in a horseshoe-shaped basin.', facilities: ['Lodges', 'Bakeries', 'Museums'], photo: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=500&q=80', lng: 86.711, lat: 27.806 },
  { id: 'gokyo-lakes', name: 'Gokyo Lakes', category: 'Nature', district: 'Solukhumbu', province: 1, province_name: 'Koshi', description: 'A series of breathtaking oligotrophic lakes at 4,700m, offering one of the best Everest region panoramas.', facilities: ['Trekking', 'Tea Houses'], photo: 'https://images.unsplash.com/photo-1483728642387-6c3ba6c6af5f?w=500&q=80', lng: 86.685, lat: 27.954 },
  { id: 'dharan-bhedetar', name: 'Bhedetar Viewpoint', category: 'Nature', district: 'Dhankuta', province: 1, province_name: 'Koshi', description: 'A popular hill station providing sweeping views of the plains and the Makalu Himalayan range.', facilities: ['View Tower', 'Resorts'], photo: 'https://images.unsplash.com/photo-1502466650593-b65a2c690da0?w=500&q=80', lng: 87.323, lat: 26.866 },
  { id: 'milke-danda', name: 'Milke Danda', category: 'Nature', district: 'Sankhuwasabha', province: 1, province_name: 'Koshi', description: 'A high ridge famously known as the capital of rhododendrons, blooming spectacularly in spring.', facilities: ['Trekking', 'Camping'], photo: 'https://images.unsplash.com/photo-1526462703816-7788a1e5cbaf?w=500&q=80', lng: 87.493, lat: 27.283 },
  { id: 'mai-pokhari', name: 'Mai Pokhari', category: 'Nature', district: 'Ilam', province: 1, province_name: 'Koshi', description: 'A star-shaped lake surrounded by pristine forest; a Ramsar wetland site sacred to both Hindus and Buddhists.', facilities: ['Pilgrimage', 'Nature Walks'], photo: 'https://images.unsplash.com/photo-1548625361-ecbfd27d5da1?w=500&q=80', lng: 87.927, lat: 27.009 },
  { id: 'halasi-mahadev', name: 'Halesi Mahadev', category: 'Religion', district: 'Khotang', province: 1, province_name: 'Koshi', description: 'A spectacular natural cave system revered as the "Pashupatinath of the East" by Hindus and Buddhists.', facilities: ['Cave Exploration', 'Temple'], photo: 'https://images.unsplash.com/photo-1533055640609-24b498dfd74c?w=500&q=80', lng: 86.621, lat: 27.191 },

  // Gandaki (Add a few more)
  { id: 'mardi-himal', name: 'Mardi Himal Trek', category: 'Adventure', district: 'Kaski', province: 4, province_name: 'Gandaki', description: 'A stunning, relatively new ridge trek offering incredibly close views of Machhapuchhre (Fishtail) and Annapurna.', facilities: ['Trekking', 'Tea Houses'], photo: 'https://images.unsplash.com/photo-1522069213568-d0e7e174b01e?w=500&q=80', lng: 83.864, lat: 28.455 },
  { id: 'kagbeni', name: 'Kagbeni Village', category: 'Heritage', district: 'Mustang', province: 4, province_name: 'Gandaki', description: 'A fascinating medieval-looking village with mud-packed houses, acting as the gateway to Upper Mustang.', facilities: ['Lodges', 'Monastery'], photo: 'https://images.unsplash.com/photo-1602489953282-3536da900138?w=500&q=80', lng: 83.784, lat: 28.836 },
  { id: 'tsho-rolpa', name: 'Tsho Rolpa Glacial Lake', category: 'Nature', district: 'Dolakha', province: 3, province_name: 'Bagmati', description: 'One of the largest glacial lakes in Nepal, situated in the dramatic Rolwaling Valley at 4,580m.', facilities: ['Trekking', 'Camping'], photo: 'https://images.unsplash.com/photo-1502466650593-b65a2c690da0?w=500&q=80', lng: 86.475, lat: 27.859 },

  // Bagmati (Add a few more)
  { id: 'taudaha-lake', name: 'Taudaha Lake', category: 'Nature', district: 'Kathmandu', province: 3, province_name: 'Bagmati', description: 'A tranquil lake in the Kathmandu Valley, historically believed to house the serpent king Karkotak.', facilities: ['Bird Watching', 'Walking Trail'], photo: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=500&q=80', lng: 85.282, lat: 27.648 },
  { id: 'shivapuri-np', name: 'Shivapuri Nagarjun NP', category: 'Nature', district: 'Kathmandu', province: 3, province_name: 'Bagmati', description: 'The closest national park to Kathmandu, offering excellent day hikes, watershed protection, and rich biodiversity.', facilities: ['Hiking', 'Bird Watching'], photo: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=500&q=80', lng: 85.391, lat: 27.801 },
  { id: 'dakshinkali', name: 'Dakshinkali Temple', category: 'Religion', district: 'Kathmandu', province: 3, province_name: 'Bagmati', description: 'A highly revered shrine dedicated to Goddess Kali, located in a forested gorge south of Kathmandu.', facilities: ['Temple', 'Pilgrimage'], photo: 'https://images.unsplash.com/photo-1587396112521-4824d770514a?w=500&q=80', lng: 85.261, lat: 27.608 },
  
  // Lumbini (Add a few more)
  { id: 'tilaurakot', name: 'Tilaurakot (Ancient Kapilavastu)', category: 'Heritage', district: 'Kapilvastu', province: 5, province_name: 'Lumbini', description: 'The ancient capital city where Siddhartha Gautama (Lord Buddha) spent the first 29 years of his life.', facilities: ['Archaeological Ruins', 'Museum'], photo: 'https://images.unsplash.com/photo-1627883606774-601b6c006599?w=500&q=80', lng: 83.056, lat: 27.574 },
  { id: 'jagadishpur-lake', name: 'Jagadishpur Reservoir', category: 'Nature', district: 'Kapilvastu', province: 5, province_name: 'Lumbini', description: 'Nepal’s largest man-made lake and a crucial Ramsar wetland site for migratory birds.', facilities: ['Bird Watching', 'Boating'], photo: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=500&q=80', lng: 83.088, lat: 27.616 },
  { id: 'ruru-kshetra', name: 'Ruru Kshetra (Ridi)', category: 'Religion', district: 'Gulmi', province: 5, province_name: 'Lumbini', description: 'A sacred Hindu pilgrimage site at the confluence of the Kali Gandaki and Ridi rivers.', facilities: ['Temple', 'River Access'], photo: 'https://images.unsplash.com/photo-1616422285623-13fc11f26715?w=500&q=80', lng: 83.435, lat: 27.936 },
  
  // Mix
  { id: 'phoksundo-lake', name: 'Phoksundo Lake', category: 'Nature', district: 'Dolpa', province: 6, province_name: 'Karnali', description: 'Nepal’s deepest lake, famous for its mesmerizing turquoise color, located in Shey Phoksundo National Park.', facilities: ['Trekking', 'Camping'], photo: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500&q=80', lng: 82.964, lat: 29.198 },
  { id: 'langtang-valley', name: 'Langtang Valley Trek', category: 'Adventure', district: 'Rasuwa', province: 3, province_name: 'Bagmati', description: 'The "Valley of Glaciers", offering incredible alpine scenery and rich Tamang culture near the Tibetan border.', facilities: ['Trekking', 'Tea Houses'], photo: 'https://images.unsplash.com/photo-1483728642387-6c3ba6c6af5f?w=500&q=80', lng: 85.501, lat: 28.211 },
  { id: 'chitlang', name: 'Chitlang Village', category: 'Heritage', district: 'Makwanpur', province: 3, province_name: 'Bagmati', description: 'An ancient Newari settlement on the old trade route, now famous for homestays and organic farming.', facilities: ['Homestays', 'Hiking'], photo: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=500&q=80', lng: 85.165, lat: 27.632 },
  { id: 'gorkha-durbar', name: 'Gorkha Durbar', category: 'Heritage', district: 'Gorkha', province: 4, province_name: 'Gandaki', description: 'The historic palace of King Prithvi Narayan Shah, perched dramatically on a fortified hilltop.', facilities: ['Palace Tour', 'Museum'], photo: 'https://images.unsplash.com/photo-1549429402-9ebef050cc52?w=500&q=80', lng: 84.628, lat: 28.001 },
  { id: 'manaslu-circuit', name: 'Manaslu Circuit', category: 'Adventure', district: 'Gorkha', province: 4, province_name: 'Gandaki', description: 'An epic, challenging tea-house trek circling the world’s 8th highest peak, crossing the Larkya La pass.', facilities: ['Trekking', 'Lodges'], photo: 'https://images.unsplash.com/photo-1522069213568-d0e7e174b01e?w=500&q=80', lng: 84.631, lat: 28.551 },
  { id: 'kosithappu-wildlife', name: 'Koshi Tappu Wildlife Reserve', category: 'Nature', district: 'Sunsari', province: 1, province_name: 'Koshi', description: 'A premier bird-watching destination and the last habitat of the wild water buffalo in Nepal.', facilities: ['Wildlife Safari', 'Birding'], photo: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=500&q=80', lng: 86.953, lat: 26.621 },
  { id: 'kanchanjunga-bc', name: 'Kanchenjunga Base Camp', category: 'Adventure', district: 'Taplejung', province: 1, province_name: 'Koshi', description: 'A demanding and pristine trek to the base of the world’s 3rd highest mountain.', facilities: ['Trekking', 'Camping'], photo: 'https://images.unsplash.com/photo-1526462703816-7788a1e5cbaf?w=500&q=80', lng: 88.016, lat: 27.701 },
  { id: 'dhampus', name: 'Dhampus Village', category: 'Heritage', district: 'Kaski', province: 4, province_name: 'Gandaki', description: 'A beautiful Gurung village offering classic Annapurna range sunrises without rigorous trekking.', facilities: ['Homestays', 'Views'], photo: 'https://images.unsplash.com/photo-1602489953282-3536da900138?w=500&q=80', lng: 83.844, lat: 28.291 },
  { id: 'balthali', name: 'Balthali Eco-Village', category: 'Nature', district: 'Kavrepalanchowk', province: 3, province_name: 'Bagmati', description: 'A peaceful, off-the-beaten-path village retreat with terraced farms, orange orchards, and suspension bridges.', facilities: ['Eco-resorts', 'Hiking'], photo: 'https://images.unsplash.com/photo-1506148386377-5f65756cdd60?w=500&q=80', lng: 85.545, lat: 27.545 },
  { id: 'bison-hill', name: 'Dhorpatan Hunting Reserve', category: 'Adventure', district: 'Baglung', province: 4, province_name: 'Gandaki', description: 'Nepal’s only hunting reserve, famous for blue sheep and stunning high-altitude marshlands.', facilities: ['Trekking', 'Permit Hunting'], photo: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=500&q=80', lng: 83.053, lat: 28.531 },
  { id: 'doleshwor-mahadev', name: 'Doleshwor Mahadev', category: 'Religion', district: 'Bhaktapur', province: 3, province_name: 'Bagmati', description: 'Believed to be the missing head of the Kedarnath Jyotirlinga, a significant Shiva temple.', facilities: ['Temple', 'Pilgrimage'], photo: 'https://images.unsplash.com/photo-1623190289944-78db0fce29ce?w=500&q=80', lng: 85.452, lat: 27.632 },
  { id: 'palanchowk-bhagawati', name: 'Palanchowk Bhagawati', category: 'Religion', district: 'Kavrepalanchowk', province: 3, province_name: 'Bagmati', description: 'An intricately carved 5th-century stone idol of Goddess Bhagawati atop a scenic hill.', facilities: ['Temple', 'Views'], photo: 'https://images.unsplash.com/photo-1552554764-92d6e3f429bc?w=500&q=80', lng: 85.641, lat: 27.691 },
  { id: 'nar-phu', name: 'Nar Phu Valley Trek', category: 'Adventure', district: 'Manang', province: 4, province_name: 'Gandaki', description: 'A restricted area trek offering raw Tibetan culture, ancient monasteries, and rugged landscapes.', facilities: ['Trekking', 'Homestays'], photo: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&q=80', lng: 84.156, lat: 28.761 },
  { id: 'tansen-palpa', name: 'Tansen, Palpa', category: 'Heritage', district: 'Palpa', province: 5, province_name: 'Lumbini', description: 'A historic hill town renowned for Dhaka fabric, Newari architecture, and the Srinagar Danda viewpoint.', facilities: ['Shopping', 'Sightseeing'], photo: 'https://images.unsplash.com/photo-1570184488340-a35b43ceaf67?w=500&q=80', lng: 83.546, lat: 27.867 },
  { id: 'rani-mahal', name: 'Rani Mahal', category: 'Heritage', district: 'Palpa', province: 5, province_name: 'Lumbini', description: 'Known as the "Taj Mahal of Nepal", a stunning palace built on the banks of the Kali Gandaki river.', facilities: ['Palace Tour', 'River Views'], photo: 'https://images.unsplash.com/photo-1598285721200-a5cc9de915d3?w=500&q=80', lng: 83.568, lat: 27.918 },
  { id: 'supa-deurali', name: 'Supa Deurali Temple', category: 'Religion', district: 'Arghakhanchi', province: 5, province_name: 'Lumbini', description: 'A famous Hindu temple situated dramatically in a mountain gorge, surrounded by local legends.', facilities: ['Temple', 'Pilgrimage'], photo: 'https://images.unsplash.com/photo-1548625361-ecbfd27d5da1?w=500&q=80', lng: 83.111, lat: 27.981 },
  { id: ' स्वर्गद्वारी', name: 'Swargadwari', category: 'Religion', district: 'Pyuthan', province: 5, province_name: 'Lumbini', description: 'A major hilltop pilgrimage site famous for its continuous Vedic fire (Akhanda Yagya) and ashram.', facilities: ['Temple', 'Ashram'], photo: 'https://images.unsplash.com/photo-1628172826725-7ec5ef2c2c04?w=500&q=80', lng: 82.856, lat: 28.118 },
  { id: 'khaptad-np', name: 'Khaptad National Park', category: 'Nature', district: 'Doti', province: 7, province_name: 'Sudurpashchim', description: 'A unique rolling plateau featuring moorland, steep slopes, and an ashram of the Khaptad Baba.', facilities: ['Trekking', 'Camping', 'Meditation'], photo: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=500&q=80', lng: 81.042, lat: 29.351 },
  { id: 'shuklaphanta', name: 'Shuklaphanta National Park', category: 'Nature', district: 'Kanchanpur', province: 7, province_name: 'Sudurpashchim', description: 'Home to the largest herd of swamp deer in the world and exceptional tiger habitats in the Terai.', facilities: ['Jungle Safari', 'Birding'], photo: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=500&q=80', lng: 80.252, lat: 28.841 },
  { id: 'dodhara-chandani', name: 'Dodhara Chandani Bridge', category: 'Heritage', district: 'Kanchanpur', province: 7, province_name: 'Sudurpashchim', description: 'One of the longest multi-span suspension bridges in Asia, crossing the massive Mahakali river.', facilities: ['Sightseeing', 'Photography'], photo: 'https://images.unsplash.com/photo-1616857921360-31622325ab3b?w=500&q=80', lng: 80.121, lat: 28.924 },
  { id: 'bajhang-durbar', name: 'Bajhang Durbar', category: 'Heritage', district: 'Bajhang', province: 7, province_name: 'Sudurpashchim', description: 'Ruins and remnants of the ancient Malla kings’ palace offering historical insight into the far-west.', facilities: ['Historical Site'], photo: 'https://images.unsplash.com/photo-1549429402-9ebef050cc52?w=500&q=80', lng: 81.181, lat: 29.551 },
  { id: 'api-nampa', name: 'Api Nampa Conservation Area', category: 'Adventure', district: 'Darchula', province: 7, province_name: 'Sudurpashchim', description: 'A pristine, remote protected area featuring Mount Api and rich high-Himalayan biodiversity.', facilities: ['Trekking', 'Expeditions'], photo: 'https://images.unsplash.com/photo-1526462703816-7788a1e5cbaf?w=500&q=80', lng: 80.952, lat: 30.012 },
  { id: 'panchpokhari', name: 'Panch Pokhari', category: 'Nature', district: 'Sindhupalchok', province: 3, province_name: 'Bagmati', description: 'A group of five holy lakes at 4,100m, offering incredible views of the Jugal Himal range.', facilities: ['Trekking', 'Pilgrimage'], photo: 'https://images.unsplash.com/photo-1466695108335-44674aa2058b?w=500&q=80', lng: 85.731, lat: 28.031 },
  { id: 'siddha-cave', name: 'Siddha Gufa', category: 'Adventure', district: 'Tanahu', province: 4, province_name: 'Gandaki', description: 'The largest cave in Nepal, spanning nearly 500 meters deep with dramatic stalactite formations.', facilities: ['Caving', 'Guided Tours'], photo: 'https://images.unsplash.com/photo-1533055640609-24b498dfd74c?w=500&q=80', lng: 84.412, lat: 27.935 },
  { id: 'gufapokhari', name: 'Gufa Pokhari', category: 'Nature', district: 'Sankhuwasabha', province: 1, province_name: 'Koshi', description: 'A quiet, reflective lake on the Milke Danda ridge offering stunning vistas of Makalu and Kanchenjunga.', facilities: ['Trekking', 'Homestays'], photo: 'https://images.unsplash.com/photo-1550596334-7bb40a71b6bc?w=500&q=80', lng: 87.521, lat: 27.321 },
  { id: 'chandragiri', name: 'Chandragiri Hills', category: 'Nature', district: 'Kathmandu', province: 3, province_name: 'Bagmati', description: 'A major viewpoint accessed by cable car, offering sweeping panoramas of the Kathmandu Valley and Himalayas.', facilities: ['Cable Car', 'Resort', 'Bhaleshwor Temple'], photo: 'https://images.unsplash.com/photo-1502466650593-b65a2c690da0?w=500&q=80', lng: 85.203, lat: 27.653 }
];

const newFeatures = newSpots.map(spot => ({
  type: 'Feature',
  geometry: {
    type: 'Point',
    coordinates: [spot.lng, spot.lat]
  },
  properties: {
    id: spot.id,
    name: spot.name,
    category: spot.category,
    district: spot.district,
    province: spot.province,
    province_name: spot.province_name,
    description: spot.description,
    facilities: spot.facilities,
    photo: spot.photo
  }
}));

data.features = data.features.concat(newFeatures);

fs.writeFileSync(path, JSON.stringify(data, null, 2));

console.log(`Added ${newFeatures.length} new spots.`);
console.log(`Total spots is now ${data.features.length}.`);

